### ISSUE TITLE
[QUESTION] Exclude directory clang-format-all

### ISSUE THREAD

**Issue by ghost** [ElectricRCAircraftGuy/eRCaGuy_PPM_Writer#9]
Hi @ElectricRCAircraftGuy 

Greetings.

I have been using your sh script to format my cpp files and everything is working perfectly. I was wondering if there is an updated script to exclude directories, e.g. build folders since I am getting formatting from those as well.

Thanks!

**Comment by ghost** [comment]
I found out that I can use the path to the folder that I want to format

`./clang-format-all src/ --style=.clang-format`

Thanks!

**Comment by ElectricRCAircraftGuy** [comment]
I don't understand how `./clang-format-all src/ --style=.clang-format` works. That's not a script I have. Did you rename it?

Here is my latest repo with this script by the way: https://github.com/ElectricRCAircraftGuy/eRCaGuy_CodeFormatter

See my answer to your above question here: https://github.com/ElectricRCAircraftGuy/eRCaGuy_CodeFormatter/issues/5#issue-1260342122

**Comment by ghost** [comment]
Hi @ElectricRCAircraftGuy 

I used the script you posted in stackoverflow. I will check the new version since I noticed that the previous command a posted is not excluding the build directory.

**Comment by ghost** [comment]
> I don't understand how `./clang-format-all src/ --style=.clang-format` works. That's not a script I have. Did you rename it?
> 
> Here is my latest repo with this script by the way: https://github.com/ElectricRCAircraftGuy/eRCaGuy_CodeFormatter
> 
> See my answer to your above question here: [ElectricRCAircraftGuy/eRCaGuy_CodeFormatter#5 (comment)](https://github.com/ElectricRCAircraftGuy/eRCaGuy_CodeFormatter/issues/5#issue-1260342122)

Hi @ElectricRCAircraftGuy 

I have tested the new script and is working perfectly. Just one thing: The path to be excluded is being taken in the script from the absolute path nor the relative path, this works for me:

`-not \( -path "*/build/*" -prune \)`

instead of:

`-not \( -path "./build/*" -prune \)`
